name: stellarscope
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python >=3.9
  - future >=0.17.1
  - pyyaml >=5.1
  - numpy
  - scipy >=1.2.1
  - pysam >=0.19
  - intervaltree >=3.0.2
  - pandas
  - packaging
  - samtools >=1.16
  - pip
  - pip:
      - git+ssh://git@github.com/nixonlab/stellarscope.git#egg=stellarscope
