[build-system]
requires = [
    "setuptools>=80",
    "Cython",
    "pysam",
    "setuptools-scm>=8",
]
build-backend = "setuptools.build_meta"

[project]
name = "stellarscope"
description = "Single-cell Transposable Element Locus Level Analysis of scRNA Sequencing."
authors = [
    { name = "Matthew L. Bendall", email = "bendall@gwu.edu" },
    { name = "Matthew Greenig"},
    { name = "Helena Reyes-Gopar"},
]
dynamic = ["version"]
readme = "README.md"
license = {file = "LICENSE"}
requires-python = ">=3.9"

dependencies = [
    "future>=0.17.1",
    "PyYAML>=5.1",
    "numpy",
    "scipy>=1.2.1",
    "pysam>=0.19",
    "intervaltree>=3.0.2",
    "pandas",
    "packaging"
]

[project.scripts]
stellarscope = "stellarscope.__main__:stellarscope"

[project.urls]
Homepage = "https://github.com/nixonlab/stellarscope"
Issues = "https://github.com/nixonlab/stellarscope/issues"

[tool.setuptools_scm]
version_file = 'stellarscope/_version.py'

[tool.setuptools]
include-package-data = true

[tool.setuptools.package-data]
stellarscope = ["cmdopts/*.yaml"]
